### PR TITLE
Add using-transactional-scope-in-jms-to-database sample

### PR DESCRIPTION
**Pull request by dinuish94**

### CODE REVIEW

**Comment by abeykoon** [comment]
As discussed, the example need to have `DB insert and JMS send need to be in a same transaction`. Using transaction mediator can we do that? Please check with @isudana after having a look at the code.

**Comment by abeykoon** [comment]
Please remove unnecessary logging.

**Comment by abeykoon** [comment]
Please use script mediator to generate the error. @sajithaliyanage knows details.

**Comment by dinuish94** [comment]
On hold due to the issue identified in https://github.com/wso2/integration-studio-examples/issues/123

**Comment by dinuish94** [comment]
Draft PR: https://github.com/wso2/integration-studio-examples/pull/137

**Pull request closed without merging**
